name: pull request validation
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  test-sonar:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: yarn

      - name: Run unit tests
        run: yarn test:cov

      - name: show secret enviroment
        run: echo "${{ secrets.SONAR_TOKEN }}  ${{ secrets.SONAR_HOST_URL }}"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
